### ISSUE TITLE
This predict.py file can't perform well when the seen and unseen objects appear in one image

### ISSUE THREAD

**Issue by Bigwode** [salman-h-khan/ZSD_Release#2]

**Comment by Bigwode** [comment]
because it only rectangle the unseen objects, it assumes that there are only unseen objects in the image.So I want to ask a question about how to deal with the problem when the seen and unseen objects appear in one image simultaneously, especially two objects that have similiar semantic vector always tend to appear in one image.

**Comment by shafin5** [comment]
Actually, you have described a Generalized zero-shot detection scenario when the task is to recognize both seen and unseen together. In GZSD, as there can be overlapping ground-truth bounding boxes (no matter seen or unseen), a bounding box can be classified as an instance of both seen and unseen simultaneously if it satisfies a prediction score higher than a threshold. The non-maximal suppression will not make any problem here because NMS only prevents the selection of multiple similar bounding boxes of the same class, not the different ones. So, the seen and unseen detection can be treated separately in GZSD.

**Comment by Bigwode** [comment]
@shafin5 Thank you for your detailed reply.
